#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := aws_iot_subpub

CXXFLAGS += -Wno-unused-variable -Wno-unused-parameter -Wno-unused-value
CFLAGS += -Wno-unused-variable -Wno-unused-parameter -Wno-unused-value
include $(IDF_PATH)/make/project.mk
CXXFLAGS += -Wno-unused-variable -Wno-unused-parameter -Wno-unused-value
CFLAGS += -Wno-unused-variable -Wno-unused-parameter -Wno-unused-value